### ISSUE TITLE
Could be too much to ask, this is a feature request :)

### ISSUE THREAD

**Issue by zerOnepal** [k0kubun/xkremap#2]
Such a wonderful world it is, very glad to find/use what i wished so long 😄 ( i wonder how you read my mind )

Apologies pre-hand, could be too much to ask still I was wondering 🤔 if we could extend/implement following   
1. It would be easy if the dsl could be expanded in syntax like below to support multiple class type:
```
window class_not: ["gnome-terminal-server", "Emacs", "Rocket.Chat+"] do
  # emacs-like bindings
  remap 'C-b', to: 'Left'
  remap 'C-f', to: 'Right'
  remap 'C-p', to: 'Up'
  remap 'C-n', to: 'Down'
  ...
end 
 ```
2. Handle multiple config files from a directory ;) or some ENV vars 

Thanks a ton, now its time for **#emacseverywhere**
![awesomeee](http://www.gifwave.com/media/52403_despicable-me-minions-movies-falling.gif)

**Comment by k0kubun** [comment]
Thank you for using xkremap!

> It would be easy if the dsl could be expanded in syntax like below to support multiple class type:

It's already implemented. Are you sure you specify correct classes?

> Handle multiple config files from a directory ;) or some ENV vars

I guess you want to split a config file into multiple files. Added `include_config` directive for you. It searches files relatively from the config file specified by xkremap.
See https://github.com/k0kubun/xkremap/blob/v0.0.2/examples/multi_config.rb for example.

**Comment by zerOnepal** [comment]
thanks 🙇
