### ISSUE TITLE
Add Build-deps: ruby, bison

### ISSUE THREAD

**Issue by tSU-RooT** [k0kubun/xkremap#4]
Hi
I tried to build this software from small environment.
Seems like some software are required to build it.
```sh
$ make
...
make[1]: Entering directory '/home/tsr/git/xkremap/mruby'
ruby ./minirake
make[1]: ruby: Command not found

$ sudo apt install ruby
$ make
...
Command Failed: [bison -o "/home/tsr/git/xkremap/mruby/build/host/mrbgems/mruby-compiler/core/y.tab.c" "/home/tsr/git/xkremap/mruby/mrbgems/mruby-compiler/core/parse.y"]
```
Would you like writing description of build-dependencies into README?

**Comment by k0kubun** [comment]
Ah I've forgotten it. mruby requires ruby to build...
Added description about it https://github.com/k0kubun/xkremap#build-dependencies. Thanks!
